# Generated by Django 5.2.4 on 2025-07-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
    ]
