# Generated by Django 5.2.4 on 2025-07-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
